config/routes.rb
Store::Application.routes.draw do
  root :to => 'static_pages#index'

  get 'index', :to => 'static_pages#index'
  get 'join', :to => 'static_pages#join'
  post 'register', :to => 'static_pages#register'
  get 'sign_in', :to => 'static_pages#signin'
  get 'about', :to => 'static_pages#about'
  get 'sign_out', :to => 'sessions#destroy'

  resources :sessions, :only => [ :new, :create, :destroy ]

  namespace :usercp do
    resources :profile
    resources :products
    resources :categories do
      resources :subcategories
    end
  end

  match ':category_name' => 'category#show', as: :category_show, via: :get
  match ':category_name/:subcategory_name' => 'subcategories#show', as: :category_subcategory, via: :get

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/category.rb
class Category < ActiveRecord::Base
  extend FriendlyId
  attr_accessible :name, :exclusive
  has_many :subcategories
  has_many :products

  validates :name, :presence => true

  friendly_id :name, :use => :slugged
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :code, :name, :description, :notes, :price, :image, :category_id, :subcategory_id, :user_id
  has_attached_file :image, :styles => { :medium => "300x300", :thumb => "100x100" }, :default_url => "/images/:style/missing.png"
  belongs_to :category
  belongs_to :subcategory
  belongs_to :user

  validates :name, :presence => true
  validates :price, :numericality => true
  validates :user_id, :presence => true
  validates_attachment :image, :size => { :in =>  0..5.megabytes }
  validates_attachment_content_type :image, :content_type => [ 'image/jpeg', 'image/png' ]
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
  extend FriendlyId
  belongs_to :category
  has_many :products
  attr_accessible :name, :category_id, :order

  validates :name, :presence => true
  validates_presence_of :category

  friendly_id :name, :use => :slugged
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :email, :dob, :password
  before_create :encrypt_password
  before_save { |user| user.email = user.email.downcase }
  has_many :products

  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :email, :presence => true, uniqueness: { case_sensitive: false }
  validates :password, :presence => true, :length => { :minimum => 6, :maximum => 100 }

  def self.authenticate(email, password)
    user = find_by_email(email)
    print user
    if user && user.password == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user

  private
  def current_user
    User.find(session[:user_id]) rescue nil
  end

  def authenticate_user!
    render file: 'public/404', format: :html, status: :not_found unless current_user
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :find_category, :only => [:show]
  def index

  end

  def show

  end

  private
  def find_category
    @category = Category.find params[:id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end

  def join
    @user = User.new
  end

  def register
    @user = User.new(params[:user])

    if @user.save
      render :index
    else
      @errors = @user.errors.full_messages
      render :register
    end
  end

  def show

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    t = params[:user]
    user = User.authenticate(t[:email], t[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url, :notice => I18n.t('static_pages.logged_in')
    else
      flash.notice = I18n.t('static_pages.invalid_login')
      redirect_to sign_in_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => I18n.t('static_pages.logged_out')
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index

  end

  def join
    redirect_to root_path if current_user
    @user = User.new
  end

  def register
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_path
    else
      @errors = @user.errors.full_messages
      render :join
    end
  end

  def signin
    if current_user
      redirect_to root_path
    else
      @user = User.new
    end
  end

  def signout
  end
end

app/controllers/usercp/categories_controller.rb
class Usercp::CategoriesController < ApplicationController
  before_filter :find_category, :only => [ :edit, :update, :show, :destroy ]
  before_filter :authenticate_user!
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new( params[:category] )

    if @category.save
      redirect_to usercp_category_path( @category )
    else
      render :new
    end
  end

  def show
    respond_to do |format|
      format.json { render :json => @category.subcategories }
      format.html
    end
  end

  def update
    if @category.update_attributes params[ :category ]
      redirect_to usercp_category_path( @category )
    else
      render :new
    end
  end

  private
  def find_category
    @category = Category.find( params[:id] )
  end
end

app/controllers/usercp/products_controller.rb
class Usercp::ProductsController < ApplicationController
  before_filter :find_product, :only => [ :edit, :update, :destroy, :show ]
  before_filter :authenticate_user!, :only => [ :index, :new, :edit, :update, :destroy, :create ]

  def index
    @products = Product.where("user_id = #{current_user.id}")
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new params[:product]
    @product.user = current_user

    if @product.save
      redirect_to usercp_product_path ( @product )
    else
      render :new
    end
  end

  def update
    @product.user = current_user
    if @product.update_attributes params[ :product ]
      redirect_to usercp_product_path ( @product )
    else
      render :edit
    end
  end

  private
  def find_product
    @product = Product.find params[:id]
  end
end

app/controllers/usercp/profile_controller.rb
class Usercp::ProfileController < ApplicationController
  before_filter :find_user, only: [ :edit, :update, :destroy ]
  before_filter :authenticate_user!

  def index
    @user = current_user
  end

  def update
    if @user.update_attributes params[:user]
      redirect_to usercp_profile_index_path
    else
      render :edit
    end
  end

  private
  def find_user
    @user = User.find params[:id]
  end
end

app/controllers/usercp/subcategories_controller.rb
class Usercp::SubcategoriesController < ApplicationController
  before_filter :authenticate_user!, :find_category
  before_filter :find_subcategory, :only => [:edit, :update, :destroy, :show]

  def index
    @subcategories = @category.subcategories.all
  end

  def new
    @subcategory = Subcategory.new
  end

  def create
    @subcategory = Subcategory.new params[:subcategory]

    if @subcategory.save
      redirect_to usercp_category_subcategory_path( @subcategory.category.id, @subcategory )
    else
      render :new
    end
  end

  def update
    if @subcategory.update_attributes( params[:subcategory] )
      redirect_to usercp_category_subcategory_path( @subcategory.category.id, @subcategory )
    else
      render :edit
    end
  end

  private
  def find_category
    @category = Category.find(params[:category_id])
    rescue ActiveRecord::RecordNotFound
      render file: 'public/404', format: :html, status: :not_found
  end

  def find_subcategory
    @subcategory = @category.subcategories.find( params[ :id ] )
    rescue ActiveRecord::RecordNotFound
      render file: 'public/404', format: :html, status: :not_found
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/categories/show.html.haml
%h1 Category!!

app/views/home/_register_form.html.haml
= simple_form_for :user, :url => '/home/register', :method => 'post' do |f|
  = f.input :first_name
  = f.input :last_name
  = f.input :email
  = f.input :password
  = f.button :submit
  - if @user.errors.any?
    - @user.errors.full_messages.each do |msg|
      %li= msg

app/views/home/register.html.haml
%h1 Register
= render 'register_form', :user => @user

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_nav.html.haml
- if current_user
  = link_to t('profile.manage_profile'), usercp_profile_index_path
  = link_to t('products.manage_products'), usercp_products_path
  = link_to t('categories.manage_categories'), usercp_categories_path
  = link_to t('static_pages.sign_out'), sign_out_path
- else
  = link_to t('static_pages.sign_in'), sign_in_path
  = link_to t('static_pages.join'), join_path

app/views/layouts/application.html.haml
!!!5
%html{ :class => "#{controller_name} #{controller_name}-#{action_name}" }
  %head
    - if content_for?(:title)
      %title= yield(:title)
    - else
      %title= t('main.title')
    = yield( :head )
    = stylesheet_link_tag "application", :media => 'all'
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = render '/layouts/nav'
    = render '/layouts/messages'
    = yield

app/views/static_pages/_login_form.html.haml
=simple_form_for @user, :url => '/sessions' do |f|
  =f.input :email
  =f.input :password
  =f.submit :submit
  -if @user.errors.any?
    - @user.errors.full_messages_each
    %li= msg

app/views/static_pages/_register_form.html.haml
= simple_form_for :user, :url => '/register', :method => 'post' do |f|
  = f.input :first_name
  = f.input :last_name
  = f.input :email
  = f.input :password
  = f.submit :submit
  - if @user.errors.any?
    - @user.errors.full_messages.each do |msg|
      %li= msg

app/views/static_pages/index.html.haml
%h1= t('static_pages.welcome_message')

app/views/static_pages/join.html.haml
%h1= t('static_pages.register')
= render 'register_form', :user => @user

app/views/static_pages/show.html.haml
%h1 Show Register
= render 'register_form', :user => @user

app/views/static_pages/signin.html.haml
%h1= t('static_pages.login')
= render 'login_form', :user => @user

app/views/usercp/categories/_form.html.haml
= simple_form_for [ :usercp, category ] do |f|
  = f.input :name
  = f.submit :submit
  - if @category.errors.any?
    - @category.errors.inspect
    - @category.errors.messages do
      %li= msg

app/views/usercp/categories/edit.html.haml
%h1= t('categories.edit')
= render 'form', :category => @category

app/views/usercp/categories/index.html.haml
%h1= t('categories.title')

- @categories.each do |c|
  %div
    %h3= c.name
    %li= link_to t('categories.show'), usercp_category_path( c )
    %li= link_to t('categories.edit'), edit_usercp_category_path( c )

%div= link_to t('categories.new'), new_usercp_category_path

app/views/usercp/categories/new.html.haml
%h1= t('categories.new')
= render 'form', :category => @category

app/views/usercp/categories/show.html.haml
%h1= @category.name
=link_to t('categories.edit'), edit_usercp_category_path( @category.id )

%h2= t('categories.subcategories_for')
- @category.subcategories.each do |s|
  %li= link_to s.name, usercp_category_subcategory_path( @category, s )

%li= link_to t('subcategories.new'), new_usercp_category_subcategory_path( @category )

app/views/usercp/products/_form.html.haml
%script p = new Product();

= simple_form_for [ :usercp, product ] do |f|
  = f.input :code
  = f.input :name
  = f.input :price
  = f.input :image, :as => :file
  = f.association :category, :input_html => { :onchange => 'p.getSubcategories(this)' }
  = f.association :subcategory, collection: Subcategory.where(:category_id => product.category)
  = f.input :description, :as => :text, :input_html => { :cols => 50, :rows => 3 }
  = f.input :notes
  = f.button :submit
  - if @product.errors.any?
    - @product.errors.each do |msg|
      %li= msg

app/views/usercp/products/edit.html.haml
= render 'form', :product => @product

app/views/usercp/products/index.html.haml
%h1= t('products.title')

- @products.each do |p|
  %div
    %h3= p.name
    %img{ :src => p.image.url(:thumb) }
    %div= p.description
    %div= p.price
    = link_to t('products.edit'), edit_usercp_product_path(p.id)

= link_to t('products.new'), new_usercp_product_path

app/views/usercp/products/new.html.haml
= render 'form', :product => @product

app/views/usercp/products/show.html.haml
%h1=@product.name

%div=@product.description
%div=@product.price
%img{:src => @product.image.url(:medium) }

app/views/usercp/profile/_user_form.html.haml
= simple_form_for user, :url => "/usercp/profile/#{user.id}", :method => 'PUT' do |f|
  = f.input :first_name
  = f.input :last_name
  = f.input :email
  = f.button :submit
  - if @user.errors.any?
    - @user.errors.messages.each do |msg|
      %li=msg

app/views/usercp/profile/edit.html.haml
%h1 Edit Profile
= render 'user_form', :user => @user

app/views/usercp/profile/index.html.haml
%h1= t('profile.title')

%div=@user.first_name
%div=@user.last_name
%div=@user.email

= link_to t('profile.edit'), edit_usercp_profile_path(@user.id)

app/views/usercp/subcategories/_form.html.haml
= simple_form_for [:usercp, category, subcategory] do |f|
  = f.input :name
  = f.association :category, :selected => category.id
  = f.input :order
  = f.submit :submit
- if @subcategory.errors.any?
  - @subcategory.errors.full_messages_each do
    %li= msg

app/views/usercp/subcategories/edit.html.haml
%h1= t('subcategories.edit')
= render 'form', :category => @category, :subcategory => @subcategory

app/views/usercp/subcategories/index.html.haml
%h1= @category.name
- @category.subcategories.each do |s|
  %p= s.name
  %p= s.category.name
  %p= s.order
  = link_to t('subcategories.edit'), edit_usercp_category_subcategory_path( @category, s )

= link_to t('subcategories.new'), new_usercp_category_subcategory_path( @category )

app/views/usercp/subcategories/new.html.haml
%h1= t('subcategories.new')
= render 'form', :category => @category, :subcategory => @subcategory

app/views/usercp/subcategories/show.html.haml
%h1= @subcategory.name
%p= @subcategory.category.name
%p= @subcategory.order
= link_to t('subcategories.edit'), edit_usercp_category_subcategory_path(@category, @subcategory )